from typing import List, Dict, Any

REPLAY_SIGNALS: List[Dict[str, Any]] = [
    # Eli Lilly - Orforglipron & Retatrutide Signals
    {
        "external_id": "ct-lilly-orforglipron-001",
        "title": "Phase 3 ATTAIN-1 Trial Status Update: Oral GLP-1 Orforglipron Achieves Primary Weight Loss Endpoint",
        "summary": "Eli Lilly updated ClinicalTrials.gov record for NCT05672836 (ATTAIN-1). The once-daily oral non-peptide GLP-1 receptor agonist Orforglipron achieved significant body weight reduction (-14.7% at 36 weeks) in adults with obesity without diabetes.",
        "source": "ClinicalTrials.gov",
        "url": "https://clinicaltrials.gov/study/NCT05672836",
        "published_date": "2026-06-15",
        "competitor": "Eli Lilly",
        "therapeutic_area": "Obesity / Oral GLP-1",
        "threat_level": "high",
        "relevance_score": 9,
        "rationale": "Direct Phase 3 readout for non-peptide oral GLP-1. Threatens injectable GLP-1 market share due to patient preference for oral dosing without food restrictions.",
        "recommended_action": "Brief commercial team",
        "action_justification": "Prepare market positioning comparison against oral formulations and evaluate patient retention strategies for injectables.",
        "scout_reason": "Direct Phase 3 trial readout for a major competitor oral obesity therapeutic.",
        "is_replay": True
    },
    {
        "external_id": "pubmed-lilly-retatrutide-002",
        "title": "Triple GIP/GLP-1/Glucagon Agonist Retatrutide Demonstrates 24.2% Weight Reduction and Hepatic Steatosis Clearance",
        "summary": "New publication in the New England Journal of Medicine details 48-week Phase 2 sub-analysis of Retatrutide (LY3437943). Patients achieved up to 24.2% mean weight reduction and >80% reduction in liver fat content in MASH patients.",
        "source": "PubMed",
        "url": "https://pubmed.ncbi.nlm.nih.gov/38910245/",
        "doi": "10.1056/NEJMoa2301972",
        "published_date": "2026-06-22",
        "competitor": "Eli Lilly",
        "therapeutic_area": "Obesity / MASH",
        "threat_level": "high",
        "relevance_score": 10,
        "rationale": "Retatrutide sets the highest efficacy bar in obesity and MASH. Represents a paradigm shift toward triple agonism.",
        "recommended_action": "Escalate to Market Access",
        "action_justification": "Assess multi-indication value proposition (obesity + liver disease) and pricing pressure implications.",
        "scout_reason": "High-impact NEJM study detailing benchmark weight loss and MASH data for Retatrutide.",
        "is_replay": True
    },
    {
        "external_id": "rss-lilly-capacity-003",
        "title": "Eli Lilly Announces $5.3B Expansion of Lebanon, Indiana Manufacturing Site for Active Pharmaceutical Ingredients",
        "summary": "Press release detailing major capital investment to expand peptide API production capacity for Tirzepatide and Orforglipron to overcome supply constraints.",
        "source": "Pharma News RSS",
        "url": "https://www.lilly.com/news/stories/indiana-manufacturing-expansion",
        "published_date": "2026-06-28",
        "competitor": "Eli Lilly",
        "therapeutic_area": "Supply Chain & Capacity",
        "threat_level": "medium",
        "relevance_score": 7,
        "rationale": "Resolving supply chain bottlenecks will unlock higher commercial volume and accelerate global market entry.",
        "recommended_action": "Update battle card",
        "action_justification": "Reflect resolved supply bottleneck timeline in competitor commercial forecasting models.",
        "scout_reason": "Supply chain expansion announcement impacts competitor market distribution capacity.",
        "is_replay": True
    },
    {
        "external_id": "pubmed-lilly-combo-004",
        "title": "Preclinical Synergistic Efficacy of Orforglipron Combined with Selective Amylin Agonists in Primate Models",
        "summary": "Abstract presented at ADA 2026 showing oral Orforglipron combined with novel amylin analog achieves superior fat mass reduction while preserving lean muscle mass.",
        "source": "PubMed",
        "url": "https://pubmed.ncbi.nlm.nih.gov/38991001/",
        "published_date": "2026-07-02",
        "competitor": "Eli Lilly",
        "therapeutic_area": "Combination Therapies",
        "threat_level": "medium",
        "relevance_score": 8,
        "rationale": "Signals Lilly's strategy to combine oral GLP-1 with amylin to target body composition quality and muscle preservation.",
        "recommended_action": "Monitor",
        "action_justification": "Track early clinical transition of Lilly's oral combination pipeline.",
        "scout_reason": "Abstract indicates strategic pivot to oral combination therapy targeting muscle preservation.",
        "is_replay": True
    },

    # Roche - CT-996 & CT-388 Signals
    {
        "external_id": "ct-roche-ct996-005",
        "title": "Phase 1b Data Release: Roche Oral GLP-1 Agonist CT-996 Demonstrates 6.1% Placebo-Adjusted Weight Loss at 4 Weeks",
        "summary": "Roche published interim Phase 1b clinical trial results (NCT06213456) for CT-996 in adults with obesity. Once-daily oral administration showed favorable tolerability without food effect.",
        "source": "ClinicalTrials.gov",
        "url": "https://clinicaltrials.gov/study/NCT06213456",
        "published_date": "2026-06-10",
        "competitor": "Roche",
        "therapeutic_area": "Oral GLP-1",
        "threat_level": "high",
        "relevance_score": 9,
        "rationale": "Rapid weight loss at 4 weeks positions CT-996 as a formidable oral GLP-1 competitor following Roche's acquisition of Carmot Therapeutics.",
        "recommended_action": "Brief commercial team",
        "action_justification": "Benchmark CT-996 4-week weight loss against early-stage oral competitors.",
        "scout_reason": "Clinical status update for Roche's lead oral obesity asset acquired from Carmot.",
        "is_replay": True
    },
    {
        "external_id": "pubmed-roche-ct388-006",
        "title": "Once-Weekly Dual GIP/GLP-1 Receptor Agonist CT-388 Shows 18.8% Weight Loss at 24 Weeks in Phase 1b Study",
        "summary": "Lancet Diabetes & Endocrinology paper reporting Phase 1b study results for Roche's subcutaneous dual agonist CT-388, showing robust glycemic control and potent body weight reduction.",
        "source": "PubMed",
        "url": "https://pubmed.ncbi.nlm.nih.gov/38890123/",
        "published_date": "2026-06-18",
        "competitor": "Roche",
        "therapeutic_area": "Obesity / Dual Agonism",
        "threat_level": "high",
        "relevance_score": 8,
        "rationale": "Solidifies Roche's entry into injectable dual GLP-1/GIP agonists, setting up direct competition with Tirzepatide.",
        "recommended_action": "Update battle card",
        "action_justification": "Incorporate CT-388 efficacy parameters into dual agonist comparison matrix.",
        "scout_reason": "Lancet publication detailing 24-week efficacy for Roche's injectable obesity drug.",
        "is_replay": True
    },
    {
        "external_id": "rss-roche-patent-007",
        "title": "Roche Files Patent for High-Bioavailability Solid Formulations of Small Molecule Peptidomimetic Incretins",
        "summary": "WIPO patent application WO2026/098765 reveals Roche's proprietary permeation enhancer platform designed to boost oral peptide absorption beyond 5%.",
        "source": "Pharma News RSS",
        "url": "https://wipo.int/patents/WO2026098765",
        "published_date": "2026-06-25",
        "competitor": "Roche",
        "therapeutic_area": "Drug Delivery Platforms",
        "threat_level": "medium",
        "relevance_score": 7,
        "rationale": "Patent filing indicates Roche is building a defensible moat around oral formulation technology.",
        "recommended_action": "Monitor",
        "action_justification": "Watch for intellectual property litigation or cross-licensing moves.",
        "scout_reason": "Patent filing revealing proprietary oral drug delivery enhancement technology.",
        "is_replay": True
    },

    # Pfizer - Danuglipron Signals
    {
        "external_id": "rss-pfizer-danuglipron-008",
        "title": "Pfizer Selects Preferred Once-Daily Formulation for Oral GLP-1 Agonist Danuglipron; Advances to Phase 2b",
        "summary": "Pfizer press release announcing pharmacokinetic optimization of once-daily Danuglipron modified-release tablet showing acceptable liver transaminase safety profile.",
        "source": "Pharma News RSS",
        "url": "https://www.pfizer.com/news/press-release/danuglipron-once-daily-advancement",
        "published_date": "2026-06-05",
        "competitor": "Pfizer",
        "therapeutic_area": "Oral GLP-1",
        "threat_level": "medium",
        "relevance_score": 7,
        "rationale": "Pfizer re-enters the oral GLP-1 race after addressing previous twice-daily tolerability and liver enzyme concerns.",
        "recommended_action": "Monitor",
        "action_justification": "Track Phase 2b enrollment rates and liver safety monitoring protocols.",
        "scout_reason": "Pipeline pivot announcement for Pfizer's once-daily oral GLP-1 candidate.",
        "is_replay": True
    },

    # Amgen - MariTide (AMG 133) Signals
    {
        "external_id": "ct-amgen-maritide-009",
        "title": "Amgen Initiates Global Phase 3 MARITIME Trial of MariTide (GIPR Antagonist / GLP-1 Agonist) with Monthly/Quarterly Dosing",
        "summary": "ClinicalTrials.gov entry NCT06451234 confirms trial initiation for MariTide across 1,800 participants. Study tests extended dosing intervals up to once every 12 weeks for weight maintenance.",
        "source": "ClinicalTrials.gov",
        "url": "https://clinicaltrials.gov/study/NCT06451234",
        "published_date": "2026-06-12",
        "competitor": "Amgen",
        "therapeutic_area": "Long-Acting Obesity Biologics",
        "threat_level": "high",
        "relevance_score": 9,
        "rationale": "Extended monthly/quarterly dosing schedules present a major compliance advantage over weekly injections.",
        "recommended_action": "Brief commercial team",
        "action_justification": "Assess potential patient preference shift toward less frequent administration models.",
        "scout_reason": "Phase 3 initiation for Amgen's antibody-peptide conjugate with quarterly dosing potential.",
        "is_replay": True
    },
    {
        "external_id": "pubmed-amgen-bone-010",
        "title": "Bone Mineral Density Trajectories in Patients Receiving GIPR Antibody Antagonism: 52-Week Biomarker Analysis",
        "summary": "Journal of Bone and Mineral Research paper finding no detrimental effect on BMD or bone turn-over markers during long-term MariTide therapy.",
        "source": "PubMed",
        "url": "https://pubmed.ncbi.nlm.nih.gov/38765432/",
        "published_date": "2026-06-29",
        "competitor": "Amgen",
        "therapeutic_area": "Safety & Tolerability",
        "threat_level": "low",
        "relevance_score": 6,
        "rationale": "Resolves key regulatory concern regarding GIP receptor antagonism and bone safety.",
        "recommended_action": "Update battle card",
        "action_justification": "Update safety section of MariTide competitor analysis file.",
        "scout_reason": "Publication addressing bone safety profile of GIP antibody antagonist mechanism.",
        "is_replay": True
    },

    # Viking Therapeutics - VK2735 Signals
    {
        "external_id": "pubmed-viking-vk2735-011",
        "title": "Phase 2 VENTURE Trial Results: Oral Tablet VK2735 Achieves Up to 3.3% Weight Reduction in 28 Days",
        "summary": "Nature Medicine manuscript presenting Phase 2 clinical data for Viking Therapeutics' oral dual GLP-1/GIP agonist VK2735, showing dose-dependent weight loss with mild GI side effects.",
        "source": "PubMed",
        "url": "https://pubmed.ncbi.nlm.nih.gov/38812345/",
        "published_date": "2026-06-08",
        "competitor": "Viking Therapeutics",
        "therapeutic_area": "Oral Dual Agonist",
        "threat_level": "high",
        "relevance_score": 8,
        "rationale": "Viking's oral VK2735 data makes it a prime M&A target or formidable independent contender in oral incretins.",
        "recommended_action": "Brief commercial team",
        "action_justification": "Analyze Viking's clinical timeline and potential big pharma acquisition scenarios.",
        "scout_reason": "Phase 2 publication for high-profile biotech oral obesity candidate.",
        "is_replay": True
    },
    {
        "external_id": "rss-viking-phase3-012",
        "title": "Viking Therapeutics Reaches Agreement with FDA on End-of-Phase 2 Design for Subcutaneous VK2735 Phase 3 Program",
        "summary": "Biotech press release confirming alignment with FDA on primary endpoints for 52-week Phase 3 registration studies in obesity and T2D.",
        "source": "Pharma News RSS",
        "url": "https://vikingtherapeutics.com/news/fda-eop2-agreement",
        "published_date": "2026-06-20",
        "competitor": "Viking Therapeutics",
        "therapeutic_area": "Obesity Phase 3",
        "threat_level": "medium",
        "relevance_score": 7,
        "rationale": "Validates Viking's regulatory pathway to market for subcutaneous dual agonist.",
        "recommended_action": "Monitor",
        "action_justification": "Track Phase 3 site initiation and enrollment milestone velocity.",
        "scout_reason": "FDA regulatory alignment announcement for Phase 3 obesity trial program.",
        "is_replay": True
    },

    # Novo Nordisk - Market Position Signals (Host Company Baseline)
    {
        "external_id": "ct-novo-cagrisema-013",
        "title": "REDEFINE-1 Phase 3 Trial Headline Data: CagriSema Achieves 25.4% Weight Reduction at 68 Weeks",
        "summary": "Clinical status entry for NCT05567890. Combination of fixed-dose amylin analog Cagrilintide and GLP-1 Semaglutide delivers superior weight loss over monotherapy components.",
        "source": "ClinicalTrials.gov",
        "url": "https://clinicaltrials.gov/study/NCT05567890",
        "published_date": "2026-06-14",
        "competitor": "Novo Nordisk",
        "therapeutic_area": "Combination Obesity Biologics",
        "threat_level": "low",
        "relevance_score": 10,
        "rationale": "Core baseline data demonstrating market-leading combination therapy performance.",
        "recommended_action": "Monitor",
        "action_justification": "Benchmark competitor triple agonists against CagriSema 25.4% benchmark.",
        "scout_reason": "Primary Phase 3 headline readout for market-leading obesity combination.",
        "is_replay": True
    },
    {
        "external_id": "pubmed-novo-amycretin-014",
        "title": "First-in-Human Dosing of Oral Amycretin (Unimolecular Dual Amylin and GLP-1 Receptor Agonist): 13.1% Weight Loss at 12 Weeks",
        "summary": "Lancet publication presenting Phase 1 clinical trial of oral unimolecular co-agonist Amycretin, showing rapid dose-dependent weight reduction without severe adverse events.",
        "source": "PubMed",
        "url": "https://pubmed.ncbi.nlm.nih.gov/38711223/",
        "published_date": "2026-06-26",
        "competitor": "Novo Nordisk",
        "therapeutic_area": "Next-Gen Oral Incretins",
        "threat_level": "low",
        "relevance_score": 9,
        "rationale": "Establishes next-generation unimolecular oral drug platform.",
        "recommended_action": "Monitor",
        "action_justification": "Use oral Amycretin profile as baseline standard for oral incretin evaluation.",
        "scout_reason": "Phase 1 trial publication for unimolecular oral dual agonist.",
        "is_replay": True
    }
]
